config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :operations do
  	get 'select_categories', on: :member
  	post 'filter', on: :collection
  end

  resources :categories

  get 'page/index'

  root 'page#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :operations, join_table: :categories_operations
  validates_presence_of :name
end

app/models/operation.rb
class Operation < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :categories, join_table: :categories_operations
	accepts_nested_attributes_for :categories
	validates_presence_of :amount, :date
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :categories, dependent: :destroy
	has_many :operations, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /categories
  def index
    @categories = Category.where({:user_id => current_user.id}).order(:is_income)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @category = Category.where({:id => params[:id], :user_id => current_user.id}).first
    if not @category
      redirect_to categories_url, alert: "Category with id = '#{params[:id]}' not found!"
    end
  end

  # POST /categories
  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id
    if @category.save
      redirect_to categories_url, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to categories_url, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name, :is_income)
    end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!

  respond_to :json, :js

  # GET /operations
  def index    
    @operations = Operation.where({:user_id => current_user.id}).order(date: :desc)
  end

  # POST /operations/filter
  def filter
    @operations = Operation.where({:user_id => current_user.id})
    @operations = @operations.where({:is_income => params[:is_income] == 'true'}) if params[:filter_by_type].present?
    @operations = @operations.where('date >= ?', DateTime.strptime(params[:date1], OperationsHelper::DTFormat)) if params[:filter_date1].present?
    @operations = @operations.where('date <= ?', DateTime.strptime(params[:date2], OperationsHelper::DTFormat)) if params[:filter_date2].present?
    if params[:category_ids].present?
        params[:category_ids].each do |category_id|
          @operations = @operations.joins(:categories).where(categories: {id: params[:category_ids]}).distinct
        end
    end
    @operations = @operations.order(date: :desc)
    render :index
  end

  # GET /operations/new
  def new
    @operation = Operation.new
    @operation.user_id = current_user.id
    @operation.id = 0
    @operation.is_income = true
    @operation.date = DateTime.now
  end

  def select_categories
    @categories = Category.where("user_id = ? AND is_income = ?", current_user.id, params[:is_income] == 'true')
    @operation = Operation.where("user_id = ? AND id = ?", current_user.id, params[:operation_id]).first
    respond_to do |format|
      format.js
    end
  end

  # GET /operations/1/edit
  def edit
    @operation = Operation.where({:id => params[:id], :user_id => current_user.id}).first    
    if not @operation
      redirect_to operations_url, alert: "Operation with id = '#{params[:id]}' not found!"
    end
  end

  # POST /operations
  def create
    @operation = Operation.new(operation_params)
    @operation.user_id = current_user.id
    if @operation.save
      redirect_to operations_url, notice: 'Operation was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /operations/1
  def update    
    params[:operation][:category_ids] ||= [] 
    if @operation.update(operation_params)
      redirect_to operations_url, notice: 'Operation was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /operations/1
  def destroy
    @operation.destroy
    redirect_to operations_url, notice: 'Operation was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def operation_params
      params.require(:operation).permit(:amount, :comment, :is_income, :date, :category_ids => [])
    end

    def filter_params
      params.permit(:filter_by_type,:is_income, :filter_date1, :date1, :filter_date2, :date2, :category_ids => [])
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
	def separate_comma(number)
	  whole, decimal = number.to_s.split(".")
	  whole_with_commas = whole.chars.to_a.reverse.each_slice(3).map(&:join).join(",").reverse
	  [whole_with_commas, decimal].compact.join(".")
	end

	DTFormat = '%d/%m/%Y %H:%M:%S'
	DTFormatJS = 'dd/MM/yyyy hh:mm:ss'
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :is_income, 'Type', :class => 'control-label'%>
    <div class="controls">
      <%= f.select :is_income, [['Income',true],['Expense',false]] %>
    </div>
  </div>
  <div class="controls">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                categories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th>Type</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td>
          <% if category.is_income? %>
          Income
          <% else %>
          Expense
          <% end %>
        </td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_category_path(category), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' %>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TestApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">      
			<a class="brand" href="/">Personal bookkeeping</a>
			<ul class="nav nav-pills">
			  <li class="<%= 'active' if params[:controller] == 'categories' %>"><%= link_to "Categories", categories_path %></li>
			  <li class="<%= 'active' if params[:controller] == 'operations' %>"><%= link_to "Operations", operations_path %></li>
			</ul>

			<div class="pull-right">
				<% if user_signed_in? %>
						<span class="nav navbar-text">Logged in as <b><%= current_user.email %></b>.</span>
						<%= link_to 'Edit profile', edit_user_registration_path, :class => 'btn btn-success' %>
						<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-danger'  %>
				<% else %>
					<%= link_to "Register", new_user_registration_path, :class => 'btn btn-success'  %>
					<%= link_to "Login", new_user_session_path, :class => 'btn btn-primary'  %>
				<% end %>
			</div>
    </div>
	</div>
</div>

    <div class="container">
        <div class="row">
          <div class="span9">
            
					<% flash.each do |key, value| %>
				    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
				  <% end %>

            <%= yield %>
          </div>

          <% if user_signed_in? %>
	          <div class="span3">
	            <div class="well sidebar-nav">
	              <ul class="nav nav-list">
	                <li class="nav-header">Actions</li>
	                <li><%= link_to "Add category", new_category_path  %></li>
	                <li><%= link_to "Add operation", new_operation_path  %></li>
	              </ul>
	            </div><!--/.well -->
	          </div><!--/span3-->
	        <% end %>
        </div><!--/row-->
    </div> <!-- /container -->

  </body>
</html>

app/views/operations/_filter.html.erb
<%= form_tag(filter_operations_path, {id: 'filter_form'}) do %>

    <div class="filter">
      <label class="checkbox"><%= check_box_tag 'filter_by_type', 1, params[:filter_by_type] %>Type</label>    
      <%= select_tag :is_income, options_for_select([['Income',true],['Expense',false]], params[:is_income]) %>
    </div>

    <div class="filter">
      <label class="checkbox"><%= check_box_tag 'filter_date1', 1, params[:filter_date1] %>After</label>    
      <div id="datetimepicker1" class="input-append date">
        <% @dt = params[:date1].present? ? DateTime.strptime(params[:date1], OperationsHelper::DTFormat) : DateTime.now %>
        <%= text_field_tag :date1, @dt.utc.strftime(OperationsHelper::DTFormat), {:class => 'text_field', :id => 'datetimepicker1', :'data-format' => OperationsHelper::DTFormatJS} %>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
        </span>
      </div>
    </div>

    <div class="filter">
      <label class="checkbox"><%= check_box_tag 'filter_date2', 1, params[:filter_date2] %>Before</label>    
      <div id="datetimepicker2" class="input-append date">        
        <% @dt = params[:date2].present? ? DateTime.strptime(params[:date2], OperationsHelper::DTFormat) : DateTime.now %>
        <%= text_field_tag :date2, @dt.utc.strftime(OperationsHelper::DTFormat), {:class => 'text_field', :id => 'datetimepicker2', :'data-format' => OperationsHelper::DTFormatJS} %>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
        </span>
      </div>
    </div>

    <div id="filters" class="well">
      <% Category.where('user_id = ?', current_user.id).each do |category|%>
        <label class="checkbox">
          <%= check_box_tag "category_ids[]", category.id, params[:category_ids].present? && params[:category_ids].map(&:to_i).include?(category.id),{ :id => "product_category_ids_"+ category.id.to_s} %>
          <%= category.name %>
        </label>
      <% end %>
    </div>

    <div class="filter">
      <button class="btn btn-success">Apply filter</button>
      <a href="<%= operations_path %>" class="btn btn-danger">Reset</a>
    </div>
    
<% end %>

<script type="text/javascript">
  $(function () {
    $('#datetimepicker1').datetimepicker();
    $('#datetimepicker2').datetimepicker();
  });
</script>

app/views/operations/_form.html.erb
<%= form_for @operation, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :comment, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :comment, :class => 'text_area' %>
    </div>
  </div>  
  <div class="control-group">
    <%= f.label :is_income, 'Type', :class => 'control-label' %>
    <div class="controls">
      <%= f.select :is_income, [['Income',true],['Expense',false]] %>
    </div>
  </div>
  <div class="control-group">    
    <label class="control-label">Categories</label>
    <div class="well controls" id="categories"> 
      <% for category in Category.where("user_id = ? AND is_income = ?", @operation.user_id, @operation.is_income) %> 
      <label class="checkbox"><%= check_box_tag "operation[category_ids][]", category.id, @operation.categories.include?(category),{ :id => "product_category_ids_"+ category.id.to_s} %><%= category.name %></label>
      <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date, 'Datetime', :class => 'control-label' %>
    <div class="controls">
      <div id="datetimepicker1" class="input-append date">
        <%= f.text_field :date, :class => 'text_field', :id => 'datetimepicker1', :'data-format' => OperationsHelper::DTFormatJS, :value => @operation.date.utc.strftime(OperationsHelper::DTFormat) %>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
        </span>
      </div>
    </div>      
  </div>
  <div class="controls">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                operations_path, :class => 'btn' %>
  </div>
<% end %>

<script type="text/javascript">
  $(function () {
    $('#datetimepicker1').datetimepicker();
    $('#operation_is_income').change(function () {
      var p = $('#operation_is_income').val();        
      $.ajaxSetup({ cache: false });
      $.get('<%= url_for select_categories_operation_path(@operation) -%>', {is_income: p});
    });
  });
</script>

app/views/operations/_select_categories.html.erb
<% @categories.each do |category| %> 
 <label class="checkbox"><%= check_box_tag "operation[category_ids][]", category.id, @operation ? @operation.categories.include?(category) : false,{ :id => "product_category_ids_"+ category.id.to_s} %><%= category.name %></label>
<% end %>

app/views/operations/edit.html.erb
<%- model_class = Operation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/operations/index.html.erb
<%- model_class = Operation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= render partial: 'filter' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th>Type</th>
      <th>Categories</th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%= "-" if not operation.is_income? %> $ <%= separate_comma(operation.amount.round(2)) %></td>
        <td><%= operation.comment %></td>
        <td>
          <% if operation.is_income %>
            Income
          <% else %>
            Expense
          <% end %>
        </td>
        <td>
          <% operation.categories.each do |category| %>
            <%= category.name %><%= "," if category != operation.categories.last %>
          <% end %>
        </td>
        <td><%= operation.date.utc.strftime(OperationsHelper::DTFormat) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_operation_path(operation), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      operation_path(operation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_operation_path,
            :class => 'btn btn-primary' %>

app/views/operations/new.html.erb
<%- model_class = Operation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/operations/select_categories.js.erb
$('#categories').html("<%= j render(:partial => 'select_categories', :locals => {:categories => @categories, :operation => @operation}) %>");

app/views/page/index.html.erb
<h1>Personal income/expenses app</h1>
<hr>
<h3>Source code <a href="https://github.com/balbesina/test_app">here</a></h3>
<h3>Test it <a href="http://mysterious-inlet-2823.herokuapp.com">here</a></h3>